apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quarkus-sample
  labels:
    app: quarkus-sample
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-sample
  endpoints:
  - port: http